# This workflow will lint and test the PathToCsv repo
name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Installation
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pytest-cov
          pip install mypy
          pip install -r requirements.txt
      - name: Check formatting with black
        uses: psf/black@stable
      - name: Lint with ruff
        uses: chartboost/ruff-action@v1
      - name: Typecheck with mypy
        run: |
         mypy --install-types --non-interactive --ignore-missing-imports path_to_csv.py
      - name: Test with pytest
        run: |
          coverage run -m pytest --durations=10
          coverage report -m
          coverage html
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: htmlcov/
